Views
Owusu-Desmond/blog-app pull request #6
Opened 2022-11-02 15:38 UTC by Owusu-Desmond

In this pull request, I implemented the design from the sneak peek wireframes.
    
![All Users page wireframe](../images/blog_root_users.png) ![Single User page wireframe](../images/blog_user_page.png) ![All Posts by a given User page wireframe](../images/blog_user_all_posts.png) ![Single Post page wireframe](../images/blog_single_post.png)

2022-11-02 16:04 UTC, youmari requested changes
Hi @Owusu-Desmond , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
✔️ Great commit messages
✔️ PRO PR
✔️ No linter error 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-02 16:04 UTC, youmari commented on app/views/users/index.html.erb
> +<% end %>
- [ ] the images are not showing up so it would be better if you fix that in order to match the requirements 
![Screen Shot 2022-11-02 at 17 00 08](https://user-images.githubusercontent.com/61790587/199539929-a86eee7d-22b1-4127-a81d-6b4be8794262.png)

2022-11-02 16:39 UTC, Owusu-Desmond commented on app/views/users/index.html.erb
> +<% end %>
Hi @youmari 

Please, I think if the image does not show your side, It may be that the image `url` you specified in your database is not matching any image on a server or has internet issues because as you can see I set the correct attribute `user.photo`.

Besides, it is working here.

![Screenshot from 2022-11-02 16-37-45](https://user-images.githubusercontent.com/92303891/199548702-c1d0bc3b-ad31-42f6-8a93-237ff2b208e0.png)

2022-11-02 16:52 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @Owusu-Desmond 

Your project is complete! Great job for Making the previous reviewer's requested changes🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- List of users showing
- images ok
- users post ok
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

![tufoin](https://media.giphy.com/media/EAZlRt1IW1aPvJKSkD/giphy.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-03 06:09 UTC, youmari commented on app/views/users/index.html.erb
> +<% end %>
@Owusu-Desmond it would be better to use the `image_tag` helper provided by rails that fix the problem it may work on your side in my side it didn't

2022-11-05 00:24 UTC, merged